//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIEGENRESTABLE
    {
        public long ID { get; set; }
        public long MOVIEID { get; set; }
        public long GENRESID { get; set; }
        public bool ISACTIVE { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
    }
}
